# Generated by Django 5.2.1 on 2025-05-15 12:48

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('records', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='record',
            old_name='quantity',
            new_name='age',
        ),
        migrations.RenameField(
            model_name='record',
            old_name='price',
            new_name='salary',
        ),
    ]
